### ISSUE TITLE
[feat] 검색 엔진 최적화(SEO)

### ISSUE THREAD

**Issue by puputia** [bbaebak/bbaebak-nextjs#18]
### 🏋🏻 어떤 개발 사항인가요?

favicon
og:thumbnail
og:title
og:image
og:description
og (홈페이지공유용, 도장받기용)

### 💪🏻 TODO

- [x] Favicon 파일 생성 및 적용
- [x] Open Graph 메타 태그 추가
- [ ] OG 정보 확인 및 테스트

**Comment by puputia** [comment]
검색 엔진 최적화 이슈

**Comment by puputia** [comment]
홈페이지 공유용 메타태그는 완료함 
도장받기용 메타태그는 아직 
export const metadata: Metadata = {
  title: '빼박',
  description: '약속은 빼도 박도 못하니까, 확실하게 만나보세요',
  openGraph: {
    title: '빼박 약속',
    description: '약속은 빼도 박도 못하니까, 확실하게 만나보세요',
    images: [
      {
        url: '/thumbnail_home.png',
        width: 1200, // 실제 이미지 크기
        height: 630, // 실제 이미지 크기
        alt: '빼박 서비스 대표 이미지',
      },
    ],
    type: 'website',
    locale: 'ko_KR',
    siteName: '빼박',
  },
  icons: {
    icon: '/favicon.ico',
  },
};

현재 지정한 메타태그는 다음과 같음. app > layout.tsx에 존재.
