### ISSUE TITLE
[feat] Main 페이지 개발

### ISSUE THREAD

**Issue by puputia** [bbaebak/bbaebak-nextjs#23]
### 🏋🏻 어떤 개발 사항인가요?

빼박 서비스의 메인 페이지(홈페이지) 의 기능 개발

### 💪🏻 TODO

- [x] 메인 페이지 UI 스타일링 작업(퍼블리싱)
- [x] 메인 페이지 '밥먹자 버튼' 클릭 시, 빼박 증명서 만들기 페이지로 이동
- [x] 더 자세한 뺴박 만들기 클릭 시, 비활성화 처리
- [x] 빼박 증명서 클릭 시, 다른 사람이 만든 빼박 증명서 결과 화면으로 이동(우선, 눌러도 아무 기능이 없는 것으로 구현)
