### ISSUE TITLE
[feat] 증명서 modal

### ISSUE THREAD

**Issue by puputia** [bbaebak/bbaebak-nextjs#24]
### 🏋🏻 어떤 개발 사항인가요?

![image](https://github.com/user-attachments/assets/3a8b8633-f480-429c-99e4-cd20bfe9a24c)
증명서 페이지의 빼박하시겠습니까? 모달 입니다. 

### 💪🏻 TODO

 
![image](https://github.com/user-attachments/assets/44bcebd7-55dd-4f24-8da2-fdbf541f0c9c)
- [ ] 빼박 하시겠습니까? 모달 스타일링(퍼블리싱) 
- [ ] 빼박합니다 버튼 동작
- [ ] 빼박 싫어요 버튼 동작
