### ISSUE TITLE
[feat] 약속 도장 '빼박' 모달 기능 구현

### ISSUE THREAD

**Issue by puputia** [bbaebak/bbaebak-nextjs#43]
### 🏋🏻 어떤 개발 사항인가요?

사용자가 약속 도장을 누르면 빼박하시겠습니까? 모달이 뜨고 
빼박하기 버튼을 누르면 증명서에 도장을 찍을 수 있음 

### 💪🏻 TODO

- [x] 빼박하시겠습니까? 모달 스타일링 
- [x] 빼박하시겠습니까? 버튼 기능 구현
- [ ] 빼박을 완료했어요! 모달 스타일링
- [ ] 빼박을 완료했어요! 모달 기능 구현(잠깐 등장했다 사라지는거)
